services:
  postgres:
    image: postgres:16
    container_name: dsa-postgres
    restart: always
    environment:
      POSTGRES_DB: dsa_tracker
      POSTGRES_USER: rakesh
      POSTGRES_PASSWORD: rakesh123_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
