server:
  port: 7008

spring:
  application:
    name: dsa-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/dsa_tracker
    username: rakesh
    password: rakesh123_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # use validate/create-drop in prod as appropriate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  name: dsa-tracker
  backup:
    enabled: true
    cron: "0 0 0 * * *" # not functional right now
    max-files: 20
  github:
    username: rak626
    branch: main
    token: ${GITHUB_BACKUP_TOKEN}
    repo: dsa-tracker-backups
